#!/usr/bin/python3

import beepy
import sys

def read():
	out = ""
	while out == "":
		out = sys.stdin.readline()
	return out

# MDM module handshake
print("Recognized")
ready = read()

if ready == "Ready":
	while True:
		print("Metal?")
		detect = read()
		if detect == "Detected":
			beepy.beep(sound=1)
		else:
			beepy.beep(sound=3)

raise BaseException(ready)
